// <auto-generated />
using BouwJeBlutNV.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BouwJeBlutNV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200227203337_adding_Some_Initial_Employees")]
    partial class adding_Some_Initial_Employees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BouwJeBlutNV.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "admin@BouwJeBlutNV.be",
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "youssef@BouwJeBlutNV.be",
                            Name = "youssef"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "john@BouwJeBlutNV.be",
                            Name = "john"
                        },
                        new
                        {
                            Id = 4,
                            Department = 2,
                            Email = "kaya@BouwJeBlutNV.be",
                            Name = "kaya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
